sylius_resource:
  resources:
    sylius.room_action_chance_action:
      driver: doctrine/orm
      classes:
        controller: App\Controller\Resources\ResourceController
        model: App\Entity\RoomAction\ChanceAction
        repository: App\Repository\RoomAction\ChanceActionRepository
