sylius_resource:
  resources:
    sylius.room_action_choice:
      driver: doctrine/orm
      classes:
        controller: App\Controller\Resources\ResourceController
        model: App\Entity\RoomAction\Choice
        repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
