sylius_resource:
  resources:
    sylius.item:
      driver: doctrine/orm
      classes:
        controller: App\Controller\Resources\ResourceController
        model: App\Entity\Item
        repository: App\Repository\ItemRepository
