sylius_resource:
  resources:
    sylius.item:
      driver: doctrine/orm
      classes:
        controller: App\Controller\Resources\ResourceController
        model: App\Entity\Item
        repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
