imports:
  - { resource: 'room_action\room.yaml' }
  - { resource: 'room_action\choice.yaml' }
  - { resource: 'room_action\item_action.yaml' }
  - { resource: 'room_action\chance_action.yaml' }

sylius_resource:
  resources:
    sylius.room_action:
      driver: doctrine/orm
      classes:
        controller: App\Controller\Resources\ResourceController
        model: App\Entity\RoomAction
        repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
