sylius_resource:
    resources:
        sylius.user:
            driver: doctrine/orm
            classes:
                controller: App\Controller\Resources\ResourceController
                model: App\Entity\User
                repository: App\Repository\UserRepository
                form: App\Form\Type\User\UserType
