services:
    app.factory.user:
        class: App\Factory\UserFactory
        decorates: sylius.factory.user
        arguments: ['@app.factory.user.inner']
        public: true

    app.factory.room_action:
        class: App\Factory\RoomActionFactory
        decorates: sylius.factory.room_action
        arguments: ['@app.factory.room_action.inner']
        public: true

    app.factory.item:
        class: App\Factory\ItemFactory
        decorates: sylius.factory.item
        arguments: ['@app.factory.item.inner']
        public: true

    app.factory.room_action_choice:
        class: App\Factory\RoomAction\ChoiceFactory
        decorates: sylius.factory.room_action_choice
        arguments: ['@app.factory.room_action_choice.inner']
        public: true

    app.factory.room_action_chance_action:
        class: App\Factory\RoomAction\ChanceActionFactory
        decorates: sylius.factory.room_action_chance_action
        arguments: ['@app.factory.room_action_chance_action.inner']
        public: true

    app.factory.room_action_item_action:
        class: App\Factory\RoomAction\ItemActionFactory
        decorates: sylius.factory.room_action_item_action
        arguments: ['@app.factory.room_action_item_action.inner']
        public: true
