sylius_fixtures:
    suites:
        default:
            fixtures:
                user: ~

services:
    app.fixture.user:
        class: App\Fixture\UserFixture
        arguments:
            - '@security.user_password_encoder.generic'
            - '@sylius.repository.user'
        tags: ['sylius_fixtures.fixture']

    app.fixture.donjon:
        class: App\Fixture\RoomFixtures
        arguments:
            - '@sylius.repository.user'
            - '@sylius.repository.room_action'
            - '@sylius.factory.room_action'
            - '@sylius.factory.room_action_room'
            - '@sylius.factory.room_action_choice'
            - '@sylius.factory.room_action_chance_action'
            - '@sylius.factory.room_action_item_action'
            - '@sylius.factory.item'
            - '@sylius.repository.room_action_room'
            - '@sylius.repository.room_action_choice'
            - '@sylius.repository.room_action_chance_action'
            - '@sylius.repository.room_action_item_action'
            - '@sylius.repository.item'
        tags: ['sylius_fixtures.fixture']
