sylius_fixtures:
    suites:
        default:
            fixtures:
                user: ~

services:
    app.fixture.user:
        class: App\Fixture\UserFixture
        arguments:
            - '@security.user_password_encoder.generic'
            - '@sylius.repository.user'
            - '@app.service.generator.binder'
        tags: ['sylius_fixtures.fixture']
