services:
    app.service.generator.next_room:
        class: App\Services\Generator\NextRoomGenerator
        arguments:
            - '@sylius.repository.user'
            - '@sylius.repository.room_action'

    app.service.binder.twig_choice:
        class: App\Services\Binder\TwigChoiceBinder
        arguments:
            - '@sylius.repository.user'
