services:
    app.service.generator.next_room:
        class: App\Services\Generator\NextRoomGenerator
        arguments:
            - '@sylius.repository.user'
            - '@sylius.repository.room_action'

    app.service.binder.twig_choice:
        class: App\Services\Binder\TwigChoiceBinder
        arguments:
            - '@sylius.repository.user'

    app.service.generator.room_token:
        class: App\Services\Generator\RoomTokenGenerator
        arguments:
            - '@sylius.repository.room_action_binder'
            -
    app.service.generator.binder:
        class: App\Services\Generator\BinderGenerator
        arguments:
            - '@sylius.repository.room_action_binder'
            - '@sylius.repository.room_action'
            - '@security.token_storage'
            - '@sylius.factory.room_action_binder'

    app.service.finder.room_action:
        class: App\Services\Generator\RoomTokenGenerator
        arguments:
            - '@sylius.repository.room_action_binder'
