donjon_vanilla:
    prefix:
        en: /vanilla
        fr: /vanilla
    resource: 'donjon/donjon_vanilla.yaml'

donjon_you_died:
    methods: [GET]
    path:
        en: /you-died
        fr: /vous-etes-mort
    controller: App\Controller\YouDiedController::displayAction
