#index:
    #path: /
    #methods: [GET]
    #controller: App\Controller\DefaultController::index

login:
    path: /login
    methods: [GET, POST]
    controller: App\Controller\SecurityController::login

logout:
    path: /logout

homepage:
    path: /
    methods: [GET, POST]
    controller: App\Controller\HomeController::displayAction

forbidden:
    path: /forbidden
    methods: [GET, POST]
    controller: App\Controller\ForbiddenController::displayAction


#donjon_vanilla:
#    path: /donjon
#    resource:#

#donjon_custom:
#    path: /donjon
#    resource:
