#index:
    #path: /
    #methods: [GET]
    #controller: App\Controller\DefaultController::index

login:
    path: /login
    methods: [GET, POST]
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
