login:
    path: /login
    methods: [GET, POST]
    controller: App\Controller\SecurityController::login

logout:
    path: /logout

homepage:
    path: /
    methods: [GET, POST]
    controller: App\Controller\HomeController::displayAction

create_account:
    path: /register
    methods: [GET, POST]
    controller: App\Controller\RegistrationController::register

donjon:
    prefix:
        en: /dungeon
        fr: /donjon
    resource: 'routes/donjon.yaml'

ajax:
    prefix:
        en: /ajax
        fr: /ajax
    resource: 'routes/ajax.yaml'

error:
    path: /error
    methods: [GET, POST]
    controller: App\Controller\SecurityController::login
