imports:
    - { resource: services/aliases.yaml }
    - { resource: parameters.yaml }
    - { resource: services/resources.yaml }
    - { resource: services/fixtures.yaml }
    - { resource: services/factory.yaml }


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
#        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Controller\:
        resource: '../src/Controller/*'
        exclude: '../src/Controller/Resources'
        tags: ['controller.service_arguments']
