App\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [name]
              groups: ['sylius']
    properties:
        name:
            -   NotBlank:
                    groups: ['sylius']
