donjon_vanilla_build_next_room:
    path: /build-next-room
    methods: [GET, POST]
    controller: App\Controller\DonjonVanillaController::buildNextRoomAction

donjon_vanilla_process:
    path: /process-room/{id}
    methods: [GET, POST]
    controller: App\Controller\DonjonVanillaController::ProcessAction

donjon_vanilla_start_game:
    path: /start-game
    methods: [GET, POST]
    controller: App\Controller\DonjonVanillaController::startGameAction

donjon_vanilla_display_room:
    path: /{id}
    methods: [GET, POST]
    controller: App\Controller\DonjonVanillaController::displayRoomAction
