donjon_vanilla_display_room:
    path: /{id}
    requirements:
        id: '\d+'
    methods: [GET, POST]
    controller: App\Controller\DonjonVanillaController::displayRoomAction

donjon_vanilla_build_next_room:
    path: /build-next-room
    methods: [GET, POST]
    controller: App\Controller\DonjonVanillaController::buildNextRoomAction

donjon_vanilla_process:
    path: /process/{id}
    methods: [GET, POST]
    controller: App\Controller\DonjonVanillaController::ProcessAction

donjon_vanilla_end_game:
    path: /end-game
    methods: [GET, POST]
    controller: App\Controller\DonjonVanillaController::endGameAction
