App\Entity\RoomAction:
  type: entity
  table: room_action
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    text:
      type: string
      length: 1023
      nullable: false
    action:
      type: string
      length: 511
      nullable: true
    upVotes:
      type: integer
      nullable: false
    downVotes:
      type: integer
      nullable: false
    isStartRoomAction:
      type: boolean
    isCustomRoomAction:
      type: boolean
    looseLife:
      type: integer
  manyToOne:
    room:
      targetEntity: App\Entity\RoomAction\Room
      inversedBy: roomActions
    userBlackList:
      targetEntity: App\Entity\User
      inversedBy: blackListedRooms
  oneToMany:
    choices:
      targetEntity: App\Entity\RoomAction\Choice
      mappedBy: roomAction
