App\Entity\RoomAction\ItemAction:
  type: entity
  table: room_action_item_action
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    action:
      type: boolean
  manyToOne:
    item:
      targetEntity: App\Entity\Item
