App\Entity\RoomAction\ChanceAction:
  type: entity
  table: room_action_chance_action
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    chance:
      type: integer
  manyToOne:
    parentChoice:
      targetEntity: App\Entity\RoomAction\Choice
      mappedBy: chanceAction
      joinColumn:
        nullable: false
    successRoomAction:
      targetEntity: App\Entity\RoomAction
      joinColumn:
        name: success_room_action_id
        referencedColumnName: id
        nullable: false
    failRoomAction:
      targetEntity: App\Entity\RoomAction
      joinColumn:
        name: fail_room_action_id
        referencedColumnName: id
        nullable: false
