App\Entity\RoomAction\Room:
  type: entity
  table: room_action_room
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
      nullable: false
  oneToMany:
    roomActions:
      targetEntity: App\Entity\RoomAction
      mappedBy: room
