App\Entity\RoomAction\Choice:
    type: entity
    table: room_action_choice
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        text:
            type: string
            length: 1023
        isBackToMenu:
            type: boolean
    oneToOne:
        chanceAction:
            targetEntity: App\Entity\RoomAction\ChanceAction
            inversedBy: parentChoice
            cascade: [ PERSIST, REMOVE ]
            fetch: EAGER
    manyToOne:
        itemAction:
            targetEntity: App\Entity\RoomAction\ItemAction
            cascade: [ PERSIST, REMOVE ]
            fetch: EAGER
        roomAction:
            targetEntity: App\Entity\RoomAction
            inversedBy: choices
            joinColumn:
                nullable: false
        targetRoomAction:
            fetch: EAGER
            targetEntity: App\Entity\RoomAction
            joinColumn:
                nullable: true
