App\Entity\RoomAction:
    type: entity
    table: room_action
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable: false
        text:
            type: string
            length: 1023
            nullable: false
        action:
            type: string
            length: 511
            nullable: true
        upVotes:
            type: integer
            nullable: false
        downVotes:
            type: integer
            nullable: false
        isStartRoomAction:
            type: boolean
        isCustomRoomAction:
            type: boolean
        looseLife:
            type: integer
            nullable: true
        code:
            type: string
            nullable: false
    manyToMany:
        userBlackList:
            targetEntity: App\Entity\User
            mappedBy: blackListedRooms
    oneToMany:
        choices:
            targetEntity: App\Entity\RoomAction\Choice
            mappedBy: roomAction
    manyToOne:
        addItem:
            targetEntity: App\Entity\Item
            fetch: EAGER
