App\Entity\User:
  type: entity
  table: user
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
      nullable: false
    password:
      type: string
      length: 255
      nullable: false
    class:
      type: string
      length: 255
      nullable: true
    life:
      type: integer
      nullable: false
    roomNumber:
      type: string
      length: 255
  manyToOne:
    currentRoomAction:
      targetEntity: App\Entity\RoomAction
  oneToMany:
    blackListedRooms:
      targetEntity: App\Entity\RoomAction
      mappedBy: userBlackList
    items:
      targetEntity: App\Entity\Item
      mappedBy: user
